package skill

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// runSkillScript is written to <agentSkillsDir>/run-skill by
// EnsureRunSkillWrapper. It resolves ACTIVE (versioned) or falls back to
// flat layout, executes run.sh, and appends one USAGE.jsonl record per run.
//
// Logging uses python3 (shipped on macOS/most Linux) for JSON emission so
// shell-special characters in args can't corrupt the log. The exit code of
// run.sh is propagated; the wrapper itself only fails on resolution errors.
const runSkillScript = `#!/bin/bash
# Auto-generated by shell daemon. Do not edit — will be overwritten.
# Usage: run-skill <skill-name> [args...]
#
# Resolves the ACTIVE version (if versioned) and executes run.sh for the
# skill, logging one USAGE.jsonl record per invocation.

set -uo pipefail

SKILLS_DIR="$(cd "$(dirname "$0")" && pwd)"
if [[ $# -lt 1 ]]; then
  echo "usage: $(basename "$0") <skill-name> [args...]" >&2
  exit 64
fi

NAME="$1"; shift

# Name validation: single path segment, no slashes or dotfile sneaks.
case "$NAME" in
  */*|.*|"") echo "invalid skill name: $NAME" >&2; exit 64 ;;
esac

SKILL_ROOT="$SKILLS_DIR/$NAME"
if [[ ! -d "$SKILL_ROOT" ]]; then
  echo "skill not found: $NAME" >&2
  exit 65
fi

VERSION=""
SKILL_DIR="$SKILL_ROOT"
if [[ -f "$SKILL_ROOT/ACTIVE" ]]; then
  VERSION="$(tr -d '[:space:]' < "$SKILL_ROOT/ACTIVE")"
  case "$VERSION" in
    */*|.*|"") echo "invalid ACTIVE version: $VERSION" >&2; exit 66 ;;
  esac
  SKILL_DIR="$SKILL_ROOT/$VERSION"
fi

RUN_SH="$SKILL_DIR/run.sh"
if [[ ! -x "$RUN_SH" ]]; then
  echo "run.sh missing or not executable: $RUN_SH" >&2
  exit 67
fi

USAGE_LOG="$SKILL_DIR/USAGE.jsonl"
START_MS="$(python3 -c 'import time; print(int(time.time()*1000))')"

"$RUN_SH" "$@"
EXIT=$?

END_MS="$(python3 -c 'import time; print(int(time.time()*1000))')"
DURATION_MS=$(( END_MS - START_MS ))
TS="$(python3 -c 'import datetime; print(datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"))')"

python3 - "$TS" "$NAME" "$VERSION" "$EXIT" "$DURATION_MS" "$@" <<'PY' >> "$USAGE_LOG"
import json, sys
ts, name, version, exit_code, duration_ms, *args = sys.argv[1:]
rec = {
    "ts": ts,
    "name": name,
    "version": version or None,
    "exit_code": int(exit_code),
    "duration_ms": int(duration_ms),
    "args": args,
}
print(json.dumps(rec, separators=(",", ":")))
PY

exit "$EXIT"
`

// EnsureRunSkillWrapper writes the run-skill wrapper into dir (the per-agent
// skills directory) with executable permissions if it is missing or out of
// date. Safe to call on every daemon start.
func EnsureRunSkillWrapper(dir string) error {
	if dir == "" {
		return nil
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("mkdir skills dir: %w", err)
	}
	target := filepath.Join(dir, "run-skill")
	existing, err := os.ReadFile(target)
	if err == nil && string(existing) == runSkillScript {
		// Already up to date.
		return nil
	}
	if err := os.WriteFile(target, []byte(runSkillScript), 0o755); err != nil {
		return fmt.Errorf("write wrapper: %w", err)
	}
	// WriteFile honors the umask for new files; chmod forces executable even
	// when the umask stripped the x bits.
	if err := os.Chmod(target, 0o755); err != nil {
		return fmt.Errorf("chmod wrapper: %w", err)
	}
	return nil
}

// UsageRecord is one line in USAGE.jsonl.
type UsageRecord struct {
	TS         string   `json:"ts"`
	Name       string   `json:"name"`
	Version    *string  `json:"version"`
	ExitCode   int      `json:"exit_code"`
	DurationMS int      `json:"duration_ms"`
	Args       []string `json:"args"`
}

// UsageStats is a rollup of USAGE.jsonl records for a single skill version,
// used by the heartbeat retro to decide promote/demote/retire.
type UsageStats struct {
	Name         string
	Version      string
	Runs         int
	Successes    int
	Failures     int
	LastRun      time.Time
	AvgDuration  time.Duration
	Invocations7 int // runs in the last 7 days
}

// ReadUsage parses usageLogPath (NDJSON) into UsageRecord slice. Missing file
// returns empty slice, not an error — fresh skills have no history yet.
func ReadUsage(usageLogPath string) ([]UsageRecord, error) {
	data, err := os.ReadFile(usageLogPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var recs []UsageRecord
	for _, line := range strings.Split(strings.TrimSpace(string(data)), "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		var r UsageRecord
		if err := json.Unmarshal([]byte(line), &r); err != nil {
			// Skip corrupt lines rather than aborting — logs should be
			// read-permissive so one bad write doesn't poison the rollup.
			continue
		}
		recs = append(recs, r)
	}
	return recs, nil
}

// Rollup aggregates USAGE records into stats. Expected to be called by the
// retro for a single skill (s); caller supplies s.Dir as the version dir.
func Rollup(s *Skill) (UsageStats, error) {
	stats := UsageStats{Name: s.Name, Version: s.Version}
	recs, err := ReadUsage(filepath.Join(s.Dir, "USAGE.jsonl"))
	if err != nil {
		return stats, err
	}
	if len(recs) == 0 {
		return stats, nil
	}
	cutoff := time.Now().AddDate(0, 0, -7)
	var totalDur time.Duration
	for _, r := range recs {
		stats.Runs++
		if r.ExitCode == 0 {
			stats.Successes++
		} else {
			stats.Failures++
		}
		totalDur += time.Duration(r.DurationMS) * time.Millisecond
		if t, err := time.Parse(time.RFC3339, r.TS); err == nil {
			if t.After(stats.LastRun) {
				stats.LastRun = t
			}
			if t.After(cutoff) {
				stats.Invocations7++
			}
		}
	}
	if stats.Runs > 0 {
		stats.AvgDuration = totalDur / time.Duration(stats.Runs)
	}
	return stats, nil
}
